on: push
name: Validate
jobs:
  conftest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: test
        uses: instrumenta/conftest-action@master
        with:
          files: conftest/ingress.yml
          policy: conftest/policy
